//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DESKTOP_SERVICES.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_menuPage
    {
        public int Id { get; set; }
        public string Label { get; set; }
        public string Dossier { get; set; }
        public string Lien { get; set; }
        public string Type { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<int> Fk_menuID { get; set; }
        public string ReadOnly { get; set; }
        public string Visible { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string haveChildren { get; set; }
    }
}
