//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DESKTOP_SERVICES.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_acces
    {
        public int Id { get; set; }
        public Nullable<int> FK_ClientID { get; set; }
        public Nullable<int> FK_FonctionID { get; set; }
        public Nullable<int> FK_UtilisateurID { get; set; }
        public string Type { get; set; }
        public string DroitsDE { get; set; }
        public string DroitsCoffre { get; set; }
        public string DroitsAdmin { get; set; }
    }
}
