//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DESKTOP_SERVICES.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_reseau
    {
        public int Id { get; set; }
        public Nullable<int> FK_clientID { get; set; }
        public string PlageIP { get; set; }
        public string Gateway { get; set; }
        public string DNS { get; set; }
        public string ScopeDHCP { get; set; }
        public string ExclusionDHCP { get; set; }
        public string TypeSwitch { get; set; }
        public string RouteurModem { get; set; }
        public string ModemBridge { get; set; }
        public string Commentaire { get; set; }
    }
}
