//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DESKTOP_SERVICES.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_poste
    {
        public int Id { get; set; }
        public Nullable<int> FK_clientID { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Service { get; set; }
        public string CompteAD { get; set; }
        public string NomPoste { get; set; }
        public string IP { get; set; }
        public string ModelePoste { get; set; }
        public string CPU { get; set; }
        public string RAM { get; set; }
        public string SN { get; set; }
        public string VersionOffice { get; set; }
        public string LogicielMetier { get; set; }
    }
}
