//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DESKTOP_SERVICES.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_motDePasse
    {
        public int Id { get; set; }
        public Nullable<int> FK_ClientID { get; set; }
        public string Intitule { get; set; }
        public string Identifiant { get; set; }
        public string MotDePasse { get; set; }
        public string AccesHotline { get; set; }
        public string Commentaire { get; set; }
    }
}
