//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DESKTOP_SERVICES.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_general
    {
        public int Id { get; set; }
        public Nullable<int> FK_clientID { get; set; }
        public string Regularisation { get; set; }
        public string Activite { get; set; }
        public string Tel { get; set; }
        public string Adresse { get; set; }
        public string ImagePerimetreGeneral { get; set; }
        public string ImageContrat { get; set; }
        public string ContactNomComplet { get; set; }
        public string ContactMail { get; set; }
        public string ContactFonction { get; set; }
        public string ContactTel { get; set; }
        public string ContactGSM { get; set; }
        public string PMD { get; set; }
        public string FAI { get; set; }
        public string FAIInfo { get; set; }
        public string FAIMail { get; set; }
        public string FAIMailInfo { get; set; }
        public string Commentaire { get; set; }
        public string Domaine { get; set; }
        public string CompteAdmin { get; set; }
        public string MotDePasseAdmin { get; set; }
        public Nullable<System.DateTime> DateModifPerimetreGeneral { get; set; }
        public Nullable<System.DateTime> DateModifContrat { get; set; }
    }
}
