//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DESKTOP_SERVICES.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_dossierCommercial
    {
        public int Id { get; set; }
        public Nullable<int> FK_clientID { get; set; }
        public string CodeGestcom { get; set; }
        public string MontantContrat { get; set; }
        public string Periodicite { get; set; }
        public Nullable<System.DateTime> DateEcheance { get; set; }
        public Nullable<System.DateTime> DateEffet { get; set; }
        public string CoteRegieN1 { get; set; }
        public string CoteRegieN2 { get; set; }
        public string Ticket { get; set; }
        public string Contrat { get; set; }
        public string Regie { get; set; }
        public string VisitePreventive { get; set; }
        public string SupportVeilleTech { get; set; }
        public string PMDSurSite { get; set; }
        public string Supervision { get; set; }
        public string DE { get; set; }
        public string Audit { get; set; }
        public string Rapport { get; set; }
        public string ServeurDePret { get; set; }
        public string CarnetDeTicket { get; set; }
    }
}
