//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DESKTOP_SERVICES.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conges_conges
    {
        public int Id { get; set; }
        public Nullable<int> FK_utilisateurID { get; set; }
        public Nullable<System.DateTime> dateDeCreation { get; set; }
        public Nullable<System.DateTime> dateDebut { get; set; }
        public Nullable<System.DateTime> dateFin { get; set; }
        public Nullable<int> FK_typeCongesID { get; set; }
        public string description { get; set; }
        public string statut { get; set; }
    }
}
