//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DESKTOP_SERVICES.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GestionTemps
    {
        public int Id { get; set; }
        public Nullable<int> Fk_tacheID { get; set; }
        public Nullable<int> Fk_competenceID { get; set; }
        public Nullable<int> Fk_modeOperatoireID { get; set; }
        public Nullable<int> Fk_utilisateurID { get; set; }
        public Nullable<int> Fk_clientID { get; set; }
        public Nullable<System.DateTime> DateDuJour { get; set; }
        public string Titre { get; set; }
        public string ComplexiteTache { get; set; }
        public Nullable<double> Temps { get; set; }
        public string Facturable { get; set; }
        public string Description { get; set; }
        public string RapportIntervention { get; set; }
    }
}
