//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DESKTOP_SERVICES.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historique_affectationClient
    {
        public int Id { get; set; }
        public Nullable<int> FK_clientID { get; set; }
        public Nullable<int> FK_referentTechniqueID { get; set; }
        public Nullable<int> FK_assistantTechniqueID { get; set; }
        public Nullable<int> FK_referentCommercialID { get; set; }
        public Nullable<int> Annee { get; set; }
    }
}
