//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DESKTOP_SERVICES.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotline_suivi
    {
        public int Id { get; set; }
        public Nullable<int> FK_hotlineIncidentID { get; set; }
        public Nullable<int> FK_auteur { get; set; }
        public Nullable<System.DateTime> DateDeCreation { get; set; }
        public string Contenu { get; set; }
    }
}
