//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DESKTOP_SERVICES.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class kilometrage
    {
        public kilometrage()
        {
            this.Deplacement = new HashSet<Deplacement>();
        }
    
        public int id { get; set; }
        public string ville { get; set; }
        public Nullable<int> kilometre { get; set; }
    
        public virtual ICollection<Deplacement> Deplacement { get; set; }
    }
}
