//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DESKTOP_SERVICES.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mail_planification
    {
        public int Id { get; set; }
        public Nullable<int> FK_PlanificationID { get; set; }
        public string Client { get; set; }
        public Nullable<byte> Edition_Client { get; set; }
        public string ModeOperatoire { get; set; }
        public Nullable<byte> Edition_ModeOperatoire { get; set; }
        public string Competence { get; set; }
        public Nullable<byte> Edition_Competence { get; set; }
        public string Titre { get; set; }
        public Nullable<byte> Edition_Titre { get; set; }
        public string Description { get; set; }
        public Nullable<byte> Edition_Description { get; set; }
        public string Createur { get; set; }
        public string Editeur { get; set; }
        public string DateDeDebut { get; set; }
        public Nullable<byte> Edition_DateDeDebut { get; set; }
        public string DateDeFin { get; set; }
        public Nullable<byte> Edition_DateDeFin { get; set; }
        public string Priorite { get; set; }
        public Nullable<byte> Edition_Priorite { get; set; }
        public string Participants { get; set; }
        public Nullable<byte> Edition_Participants { get; set; }
        public string TypeMail { get; set; }
        public string OldDestinataire { get; set; }
        public string NewDestinataire { get; set; }
    }
}
