//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DESKTOP_SERVICES.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mail_hotline
    {
        public int Id { get; set; }
        public Nullable<int> FK_hotlineIncidentID { get; set; }
        public Nullable<int> FK_auteurID { get; set; }
        public string DestinataireMail { get; set; }
        public string BoolInclureSuivi { get; set; }
        public string Commentaire { get; set; }
        public string TypeMail { get; set; }
    }
}
