//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DESKTOP_SERVICES.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SERVICES20Entities : DbContext
    {
        public SERVICES20Entities()
            : base("name=SERVICES20Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<App_menu> App_menu { get; set; }
        public DbSet<App_menuDroits> App_menuDroits { get; set; }
        public DbSet<App_menuPage> App_menuPage { get; set; }
        public DbSet<Client> Client { get; set; }
        public DbSet<Client_acces> Client_acces { get; set; }
        public DbSet<Client_contact> Client_contact { get; set; }
        public DbSet<Client_dossierCommercial> Client_dossierCommercial { get; set; }
        public DbSet<Client_general> Client_general { get; set; }
        public DbSet<Client_gestionnaireCompte> Client_gestionnaireCompte { get; set; }
        public DbSet<Client_imprimante> Client_imprimante { get; set; }
        public DbSet<Client_motDePasse> Client_motDePasse { get; set; }
        public DbSet<Client_partage> Client_partage { get; set; }
        public DbSet<Client_poste> Client_poste { get; set; }
        public DbSet<Client_reseau> Client_reseau { get; set; }
        public DbSet<Client_reseauRouteurModem> Client_reseauRouteurModem { get; set; }
        public DbSet<Client_sauvegardeMateriel> Client_sauvegardeMateriel { get; set; }
        public DbSet<Client_serveur> Client_serveur { get; set; }
        public DbSet<Client_serveurPartition> Client_serveurPartition { get; set; }
        public DbSet<Client_type> Client_type { get; set; }
        public DbSet<Conges_conges> Conges_conges { get; set; }
        public DbSet<Conges_mail> Conges_mail { get; set; }
        public DbSet<Conges_typeConges> Conges_typeConges { get; set; }
        public DbSet<Connaissance_article> Connaissance_article { get; set; }
        public DbSet<Connaissance_categorie> Connaissance_categorie { get; set; }
        public DbSet<Deplacement> Deplacement { get; set; }
        public DbSet<Fichier> Fichier { get; set; }
        public DbSet<Fichier_categorie> Fichier_categorie { get; set; }
        public DbSet<Fichier_type> Fichier_type { get; set; }
        public DbSet<FileTest> FileTest { get; set; }
        public DbSet<Frais_divers> Frais_divers { get; set; }
        public DbSet<GestionTemps> GestionTemps { get; set; }
        public DbSet<Historique_affectationClient> Historique_affectationClient { get; set; }
        public DbSet<Historique_typeClient> Historique_typeClient { get; set; }
        public DbSet<Historique_utilisateurFonction> Historique_utilisateurFonction { get; set; }
        public DbSet<Hotline_incident> Hotline_incident { get; set; }
        public DbSet<Hotline_suivi> Hotline_suivi { get; set; }
        public DbSet<kilometrage> kilometrage { get; set; }
        public DbSet<Mail_associationClientUtilisateur> Mail_associationClientUtilisateur { get; set; }
        public DbSet<Mail_hotline> Mail_hotline { get; set; }
        public DbSet<Mail_parametresUtilisateur> Mail_parametresUtilisateur { get; set; }
        public DbSet<Mail_planification> Mail_planification { get; set; }
        public DbSet<NotesDeFrais_mois> NotesDeFrais_mois { get; set; }
        public DbSet<Planning_competence> Planning_competence { get; set; }
        public DbSet<Planning_modeOperatoire> Planning_modeOperatoire { get; set; }
        public DbSet<Planning_planification> Planning_planification { get; set; }
        public DbSet<Planning_planificationParticipants> Planning_planificationParticipants { get; set; }
        public DbSet<Planning_tache> Planning_tache { get; set; }
        public DbSet<Planning_typeTache> Planning_typeTache { get; set; }
        public DbSet<SAV> SAV { get; set; }
        public DbSet<ServicesApp> ServicesApp { get; set; }
        public DbSet<ServicesAppUtilisateurOnglet> ServicesAppUtilisateurOnglet { get; set; }
        public DbSet<TEMP_COUPE_DROIT> TEMP_COUPE_DROIT { get; set; }
        public DbSet<TEMP_COUPE_MATCH> TEMP_COUPE_MATCH { get; set; }
        public DbSet<TEMP_COUPE_USERVOTE> TEMP_COUPE_USERVOTE { get; set; }
        public DbSet<Utilisateur> Utilisateur { get; set; }
        public DbSet<Utilisateur_fonction> Utilisateur_fonction { get; set; }
        public DbSet<Utilisateur_profil> Utilisateur_profil { get; set; }
        public DbSet<Vue_assistantTechnique> Vue_assistantTechnique { get; set; }
        public DbSet<Vue_Association_referent_client> Vue_Association_referent_client { get; set; }
        public DbSet<Vue_commercial> Vue_commercial { get; set; }
        public DbSet<Vue_HotlineIncident> Vue_HotlineIncident { get; set; }
        public DbSet<Vue_referentTechnique> Vue_referentTechnique { get; set; }
        public DbSet<Vue_SAV> Vue_SAV { get; set; }
        public DbSet<Vue_WikiCategorieArticles> Vue_WikiCategorieArticles { get; set; }
        public DbSet<VueSpecifiqueIRD> VueSpecifiqueIRD { get; set; }
    }
}
