//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DESKTOP_SERVICES.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotesDeFrais_mois
    {
        public NotesDeFrais_mois()
        {
            this.Deplacement = new HashSet<Deplacement>();
            this.Frais_divers = new HashSet<Frais_divers>();
        }
    
        public int Id { get; set; }
        public System.DateTime date { get; set; }
        public int Utilisateur_Id { get; set; }
        public string labelMoisAnne { get; set; }
        public string validation_chefService { get; set; }
        public string validation_utilisateur { get; set; }
    
        public virtual ICollection<Deplacement> Deplacement { get; set; }
        public virtual ICollection<Frais_divers> Frais_divers { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
