//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DESKTOP_SERVICES.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAV
    {
        public int Id { get; set; }
        public Nullable<int> FK_clientID { get; set; }
        public Nullable<int> FK_ajouteParID { get; set; }
        public string Contact { get; set; }
        public string TypeMateriel { get; set; }
        public string Modele { get; set; }
        public string NumSerie { get; set; }
        public Nullable<int> FK_intervenantID { get; set; }
        public Nullable<System.DateTime> DateEntreeSAV { get; set; }
        public string Panne { get; set; }
        public string Remarque { get; set; }
        public string Statut { get; set; }
        public string Garantie { get; set; }
        public string ReferenceDossierSAV { get; set; }
    }
}
