//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DESKTOP_SERVICES.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_COUPE_MATCH
    {
        public int Id { get; set; }
        public string Eq1Label { get; set; }
        public Nullable<int> Eq1But { get; set; }
        public string Eq2Label { get; set; }
        public Nullable<int> Eq2But { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Groupe { get; set; }
        public string Etat { get; set; }
    }
}
