//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DESKTOP_SERVICES.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateur
    {
        public Utilisateur()
        {
            this.NotesDeFrais_mois = new HashSet<NotesDeFrais_mois>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Fk_fonctionID { get; set; }
        public Nullable<int> Fk_profilID { get; set; }
        public string Identifiant { get; set; }
        public string MotDePasse { get; set; }
        public int Actif { get; set; }
        public string SQL_ID { get; set; }
        public Nullable<System.DateTime> DateDeCreation { get; set; }
        public Nullable<System.DateTime> DateDerniereConnexion { get; set; }
        public string NomComplet { get; set; }
        public string Initiale { get; set; }
        public string Image { get; set; }
        public string Mail { get; set; }
        public string GSM { get; set; }
        public string TelephoneInterne { get; set; }
        public string EntiteJuridique { get; set; }
        public string DOM { get; set; }
    
        public virtual ICollection<NotesDeFrais_mois> NotesDeFrais_mois { get; set; }
    }
}
