//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DESKTOP_SERVICES.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vue_HotlineIncident
    {
        public int Id { get; set; }
        public Nullable<int> FK_clientID { get; set; }
        public string clientRaisonSociale { get; set; }
        public string TypeDemande { get; set; }
        public string Contact { get; set; }
        public string Mail { get; set; }
        public string Tel { get; set; }
        public Nullable<System.DateTime> DateDeCreation { get; set; }
        public string Description { get; set; }
        public Nullable<int> FK_creePar { get; set; }
        public string CreePar { get; set; }
        public string Etat { get; set; }
        public Nullable<int> FK_cloturePar { get; set; }
        public string NomComplet { get; set; }
        public Nullable<System.DateTime> DateDeCloture { get; set; }
        public Nullable<System.DateTime> DateProbleme { get; set; }
        public Nullable<int> FK_prisEnChargePar { get; set; }
        public string Pris_en_charge_par { get; set; }
    }
}
