//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DESKTOP_SERVICES.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vue_Association_referent_client
    {
        public int Id { get; set; }
        public int ClientID { get; set; }
        public string RaisonSociale { get; set; }
        public string TypeClient { get; set; }
        public int FK_typeClientID { get; set; }
        public Nullable<int> Référent_technique_ID { get; set; }
        public string Référent_technique { get; set; }
        public Nullable<int> Assistant_technique_ID { get; set; }
        public string Assistant_technique { get; set; }
        public Nullable<int> Référent_commercial_ID { get; set; }
        public string Référent_commercial { get; set; }
        public string EntiteJuridique { get; set; }
        public Nullable<int> FK_referentCommercialID { get; set; }
        public Nullable<int> FK_assistantTechniqueID { get; set; }
        public Nullable<int> FK_referentTechniqueID { get; set; }
    }
}
