//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DESKTOP_SERVICES.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VueSpecifiqueIRD
    {
        public int ID_Inter { get; set; }
        public string Lieu { get; set; }
        public Nullable<System.DateTime> DateDuJour { get; set; }
        public string Vide { get; set; }
        public string NomComplet { get; set; }
        public string TypeInter { get; set; }
        public Nullable<double> Temps { get; set; }
        public string MOIS { get; set; }
        public string Site { get; set; }
        public string Annee { get; set; }
    }
}
